cypress-test:
  image: cypress/browsers:node11.13.0-chrome69
  stage: test
  artifacts:
      paths:
      - cypress/screenshots
      - cypress/videos
  script:
    - npm install
    - npm update
    - $(npm bin)/cypress run -s "cypress/integration/MyShopifyWebTest.spec.js"
